use_dwpose: true
# pretrained_model_path: "runwayml/stable-diffusion-v1-5"
pretrained_model_path: '/huggingface00/hub/models--runwayml--stable-diffusion-v1-5/snapshots/1d0c4ebf6ff58a5caecab40fa1406526bca4b5b9'
pretrained_vae_path: "/models00/pretrained_models/sd-vae-ft-mse"
pretrained_appearance_encoder_path: "/models00/pretrained_models/MagicAnimate/appearance_encoder"
pretrained_controlnet_path: "/models00/pretrained_models/MagicAnimate/densepose_controlnet"
pretrained_unet_path: ""
motion_module: "/models00/pretrained_models/MagicAnimate/temporal_attention/temporal_attention.ckpt"
image_encoder_path: ""

appearance_controlnet_motion_checkpoint_path: "/work00/magic_animate_unofficial/outputs/aa_train_stage12_celebv-2023-12-19T05-00-26/checkpoints/checkpoint-steps15000.ckpt"

savename: null

fusion_blocks: "midup"

seed:           [1]
steps:          25
guidance_scale: 7.5

source_image:
    - "/work00/magic_animate_unofficial/data/movies/Scent_of_a_Woman_Alfredo_Pacino.mp4"
    # - "/work00/magic_animate_unofficial/data/mj_girls/cat2.jpg"
    # - "/work00/magic_animate_unofficial/data/mj_girls/cat.jpeg"
    # - "/work00/magic_animate_unofficial/data/mj_girls/ag1.jpeg"
    # - "/work00/magic_animate_unofficial/data/celebv/10876-2-7eMjYXRcm-0_12_0.mp4"
    # - "/work00/magic_animate_unofficial/data/celebv/10894-8-7ebsTST4bSw_1_0.mp4"

video_path:
    "/work00/magic_animate_unofficial/data/movies/Scent_of_a_Woman_Alfredo_Pacino.mp4"
    # - "/work00/magic_animate_unofficial/data/celebv/10876-2-7eMjYXRcm-0_12_0.mp4"
    # - "/work00/magic_animate_unofficial/data/celebv/10876-2-7eMjYXRcm-0_12_0.mp4"
    # - "/work00/magic_animate_unofficial/data/celebv/10894-8-7ebsTST4bSw_1_0.mp4"

inference_config: "configs/inference/magic_inference.yaml"
size: [512, 512]
L:    8 #16
S:    1
I:    0
clip: 0
offset: 0
max_length: null
video_type: "condition"
invert_video: false
save_individual_videos: false
