use_dwpose: true
# pretrained_model_path: "runwayml/stable-diffusion-v1-5"
pretrained_model_path: '/data/huggingface/hub/models--runwayml--stable-diffusion-v1-5/snapshots/1d0c4ebf6ff58a5caecab40fa1406526bca4b5b9'
pretrained_vae_path: "/data/models/pretrained_models/sd-vae-ft-mse"
pretrained_appearance_encoder_path: "/data/models/pretrained_models/MagicAnimate/appearance_encoder"
pretrained_controlnet_path: "/data/models/pretrained_models/MagicAnimate/densepose_controlnet"
pretrained_unet_path: ""
image_encoder_path: "/data/work/IP-Adapter/IP-Adapter/models/image_encoder"

appearance_controlnet_motion_checkpoint_path: "/data/work/animate_based_ap_stage2/outputs/train_stage2_w_imageencoder_celebv-2023-12-30T14-15-31/checkpoints/checkpoint-steps4000.ckpt"
motion_module: ""
# 如果指定motion_module，appearance_controlnet_motion_checkpoint_path中的motion会被覆盖
# motion_module: "/data/models/pretrained_models/MagicAnimate/temporal_attention/temporal_attention.ckpt"

savename: null

fusion_blocks: "midup"

seed:           [1]
steps:          25
guidance_scale: 7.5

context:
  context_frames: 8
  context_stride: 1
  context_overlap: 4

source_image:
    # - "/data/work/animate_based_ap_stage2/data/mj_girls/cat3.jpg"
    # - "/data/work/animate_based_ap_stage2/data/mj_girls/cat2.jpg"
    # - "/data/work/animate_based_ap_stage2/data/mj_girls/cat.jpeg"
    - "/data/work/animate_based_ap_stage2/data/emoca/82-25-854x480_affwild2_000000-000030.mp4"
    - "/data/work/animate_based_ap_stage2/data/mj_girls/ag1.jpeg"
    - "/data/work/animate_based_ap_stage2/data/mj_girls/ag1.jpeg"

    - "/data/work/animate_based_ap_stage2/data/celebv/10876-2-7eMjYXRcm-0_12_0.mp4"
    - "/data/work/animate_based_ap_stage2/data/celebv/10894-8-7ebsTST4bSw_1_0.mp4"
    - "/data/work/animate_based_ap_stage2/data/movies/Scent_of_a_Woman_Alfredo_Pacino000350_2.mp4"

video_path:
    - "/data/work/animate_based_ap_stage2/data/emoca/82-25-854x480_affwild2_000000-000030.mp4"
    - "/data/work/animate_based_ap_stage2/data/celebv/10876-2-7eMjYXRcm-0_12_0.mp4"
    - "/data/work/animate_based_ap_stage2/data/celebv/10894-8-7ebsTST4bSw_1_0.mp4"

    - "/data/work/animate_based_ap_stage2/data/celebv/10876-2-7eMjYXRcm-0_12_0.mp4"
    - "/data/work/animate_based_ap_stage2/data/celebv/10894-8-7ebsTST4bSw_1_0.mp4"
    - "/data/work/animate_based_ap_stage2/data/movies/Scent_of_a_Woman_Alfredo_Pacino000350_2.mp4"

inference_config: "configs/inference/magic_inference.yaml"
size: [512, 512]
# 长度一致
L:    8
S:    1
I:    0
clip: 0
offset: 0
max_length: null
video_type: "condition"
invert_video: false
save_individual_videos: false

unet_additional_kwargs:
  unet_use_cross_frame_attention: false
  unet_use_temporal_attention: false
  use_motion_module: true
  motion_module_resolutions:
  - 1
  - 2
  - 4
  - 8
  motion_module_mid_block: false
  motion_module_decoder_only: false
  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads: 8
    num_transformer_block: 1
    attention_block_types:
    - Temporal_Self
    - Temporal_Self
    temporal_position_encoding: true
    temporal_position_encoding_max_len: 24
    temporal_attention_dim_div: 1
  # Addition for image embeddings
  use_image_condition            : true

noise_scheduler_kwargs:
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: "linear"
