use_dwpose: true
dwpose_only_face: true
use_face_det: false
froce_text_embedding_zero: true

# pretrained_model_path: "runwayml/stable-diffusion-v1-5"
pretrained_model_path: '/data/huggingface/hub/models--runwayml--stable-diffusion-v1-5/snapshots/1d0c4ebf6ff58a5caecab40fa1406526bca4b5b9'
pretrained_vae_path: "/data/models/pretrained_models/sd-vae-ft-mse"
pretrained_appearance_encoder_path: "/data/models/pretrained_models/MagicAnimate/appearance_encoder"
pretrained_controlnet_path: "/data/models/pretrained_models/MagicAnimate/densepose_controlnet"
pretrained_unet_path: ""
image_encoder_path: "/data/work/IP-Adapter/IP-Adapter/models/image_encoder"
# image_encoder_path: ""
# appearance_controlnet_motion_checkpoint_path: "/data/work/VividVideoGeneration/outputs/train_stage3_mm_celebv_nocenterface_cfg_plusbank0.5_ipadapter_zeroembed_diffnoise_lr1e-6-2024-01-24T09-59-44/checkpoints/checkpoint-steps4000.ckpt"
appearance_controlnet_motion_checkpoint_path: "/data/work/VividVideoGeneration/outputs/train_stage1_w_imageencoder_celebv_nocenterface_cfg_train_zeroembed_plusbank0.5_ipadapter_c-2024-02-01T21-41-00/checkpoints/checkpoint-epoch-1.ckpt"

# motion_module: ""
# 如果指定motion_module，appearance_controlnet_motion_checkpoint_path中的motion会被覆盖
motion_module: "/data/models/pretrained_models/MagicAnimate/temporal_attention/temporal_attention.ckpt"

savename: null

fusion_blocks: "midup"

seed:           42
steps:          25
guidance_scale: 2

context:
  context_frames: 16
  context_stride: 1
  context_overlap: 0


source_image:
    
    # 宽脸猫
    - "/data/work/VividVideoGeneration/data/templates/cats/cat_puji/lAHPJxDj5C_y7ZbNAQDNAQA_256_256.gif"
    # 来玩呀：歪头说话
    - "/data/work/VividVideoGeneration/data/templates/cats/cat_puji/lQHPJwBWQBDmtfvNAQDNAQCwzKLp0_ObAF0FkMi-G8iNAA_256_256.gif"
    # 眨眼
    - "/data/work/VividVideoGeneration/data/templates/cats/cat_puji/lQHPJwgwO92GPHvNAQDNAQCwGSduGCPSXfYFkMjdq12HAA_256_256.gif"
    # 我ok哒：转头说话
    - "/data/work/VividVideoGeneration/data/templates/cats/cat_puji/lQHPJwmAvyZh1vvNAQDNAQCwssuGf9SMAZQFkMi_LD1tAA_256_256.gif"
    # 收到：嘴巴动作大
    - "/data/work/VividVideoGeneration/data/templates/cats/cat_puji/lQHPJxkrniYUMPvNAQDNAQCwQjnp_9iU_ewFkMi5cZPZAA_256_256.gif"
    # - "/data/work/VividVideoGeneration/data/templates/cats/cat_puji/.gif"


    - "/data/work/VividVideoGeneration/data/templates/cats/cat_puji/lAHPJv8gavWKzxLNAQDNAQA_256_256.gif"
    - "/data/work/VividVideoGeneration/data/templates/cats/cat_puji/lQHPJwBWQBDmtfvNAQDNAQCwzKLp0_ObAF0FkMi-G8iNAA_256_256.gif"
    - "/data/work/VividVideoGeneration/data/templates/cats/cat_puji/lQHPJx0K96S51PvNAQDNAQCw4tvYi7DAHh4FkMi9NzQ9AA_256_256.gif"
    - "/data/work/VividVideoGeneration/data/templates/cats/cat_puji/lQHPJxkrniYUMPvNAQDNAQCwQjnp_9iU_ewFkMi5cZPZAA_256_256.gif"

    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/sunwei_crop.jpg"  
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/cat2.jpg"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/cat2.jpg"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/cat2.jpg"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/cat2.jpg"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/cat2.jpg"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/cat2.jpg"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/cat2.jpg"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/cat2.jpg"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/cat2.jpg"

    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/cat3.jpg"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/cat3.jpg"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/cat3.jpg"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/cat3.jpg"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/cat3.jpg"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/cat3.jpg"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/cat3.jpg"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/cat3.jpg"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/cat3.jpg"

video_path:
    # - "/data/work/animate_based_ap_ctrl/data/templates/gifs/fansile.gif"
    # - "/data/work/animate_based_ap_ctrl/data/templates/gifs/shuizanchengshuifandui.gif"
    # - "/data/work/animate_based_ap_ctrl/data/templates/gifs/fansile.gif"
    # - "/data/work/animate_based_ap_ctrl/data/templates/gifs/shuizanchengshuifandui.gif"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/001.gif"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/002.gif"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/003.gif"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/004.gif"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/005.gif"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/006.gif"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/007.gif"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/008.gif"
    # - "/data/work/animate_based_ap_ctrl/data/templates/dai/009.gif"

    # - "/data/work/animate_based_ap_ctrl/data/templates/wulei/001.gif"
    # - "/data/work/animate_based_ap_ctrl/data/templates/wulei/002.gif"
    # - "/data/work/animate_based_ap_ctrl/data/templates/wulei/003.gif"
    # - "/data/work/animate_based_ap_ctrl/data/templates/wulei/004.gif"
    # - "/data/work/animate_based_ap_ctrl/data/templates/wulei/005.gif"
    # - "/data/work/animate_based_ap_ctrl/data/templates/wulei/006.gif"
    # - "/data/work/animate_based_ap_ctrl/data/templates/wulei/007.gif"
    # - "/data/work/animate_based_ap_ctrl/data/templates/wulei/008.gif"
    # - "/data/work/animate_based_ap_ctrl/data/templates/wulei/009.gif"

    # 宽脸猫
    - "/data/work/VividVideoGeneration/data/templates/cats/cat_puji/lAHPJxDj5C_y7ZbNAQDNAQA_256_256.gif"
    # 来玩呀：歪头说话
    - "/data/work/VividVideoGeneration/data/templates/cats/cat_puji/lQHPJwBWQBDmtfvNAQDNAQCwzKLp0_ObAF0FkMi-G8iNAA_256_256.gif"
    # 眨眼
    - "/data/work/VividVideoGeneration/data/templates/cats/cat_puji/lQHPJwgwO92GPHvNAQDNAQCwGSduGCPSXfYFkMjdq12HAA_256_256.gif"
    # 我ok哒：转头说话
    - "/data/work/VividVideoGeneration/data/templates/cats/cat_puji/lQHPJwmAvyZh1vvNAQDNAQCwssuGf9SMAZQFkMi_LD1tAA_256_256.gif"
    # 收到：嘴巴动作大
    - "/data/work/VividVideoGeneration/data/templates/cats/cat_puji/lQHPJxkrniYUMPvNAQDNAQCwQjnp_9iU_ewFkMi5cZPZAA_256_256.gif"
    # - "/data/work/VividVideoGeneration/data/templates/cats/cat_puji/.gif"


    - "/data/work/VividVideoGeneration/data/templates/cats/cat_puji/lAHPJv8gavWKzxLNAQDNAQA_256_256.gif"
    - "/data/work/VividVideoGeneration/data/templates/cats/cat_puji/lQHPJwBWQBDmtfvNAQDNAQCwzKLp0_ObAF0FkMi-G8iNAA_256_256.gif"
    - "/data/work/VividVideoGeneration/data/templates/cats/cat_puji/lQHPJx0K96S51PvNAQDNAQCw4tvYi7DAHh4FkMi9NzQ9AA_256_256.gif"
    - "/data/work/VividVideoGeneration/data/templates/cats/cat_puji/lQHPJxkrniYUMPvNAQDNAQCwQjnp_9iU_ewFkMi5cZPZAA_256_256.gif"


  

inference_config: "configs/inference/magic_inference.yaml"
size: [512, 512]
max_count:          1000
# 长度一致
L:    16
S:    1
I:    0
clip: 0
offset: 0
max_length: null
video_type: "condition"
invert_video: false
save_individual_videos: false

unet_additional_kwargs:
  unet_use_cross_frame_attention: false
  unet_use_temporal_attention: false
  use_motion_module: false
  motion_module_resolutions:
  - 1
  - 2
  - 4
  - 8
  motion_module_mid_block: false
  motion_module_decoder_only: false
  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads: 8
    num_transformer_block: 1
    attention_block_types:
    - Temporal_Self
    - Temporal_Self
    temporal_position_encoding: true
    temporal_position_encoding_max_len: 24
    temporal_attention_dim_div: 1
  # Addition for image embeddings
  use_image_condition            : true

noise_scheduler_kwargs:
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: "linear"
